const SHIPFUS = [
    'Abercrombie',
    'Acasta',
    'Achilles',
    'Admiral_Hipper',
    'Admiral_Graf_Spee',
    'Admiral_Hipper_',
    'Ajax',
    'Akagi_',
    'Akagi-chan',
    'Akashi',
    'Alabama',
    'Albacore',
    'Albacore_',
    'Algrie',
    'Allen_M',
    'Amagi',
    'Amazon',
    'An_Shan',
    'Aoba',
    'Aquila',
    'Arashio',
    'Archerfish',
    'Ardent',
    'Arethusa',
    'Ariake',
    'Arizona',
    'Ark_Royal',
    'Asashio',
    'Ashigara',
    'Astoria',
    'Atago',
    'Atlanta',
    'Aulick',
    'Aurora',
    'Avrora',
    'Ayanami',
    'Aylwin',
    'Bache',
    'Bailey',
    'Baltimore',
    'Baltimore_',
    'Bataan',
    'Beagle',
    'Béarn',
    'Belfast',
    'Benson',
    'Biloxi',
    'Birmingham',
    'Bismarck',
    'Black_Prince',
    'Bluegill',
    'Bogue',
    'Boise',
    'Bremerton',
    'Brooklyn',
    'Bulldog',
    'Bunker_Hill',
    'Bush',
    'California',
    'Carabiniere',
    'Casablanca',
    'Cassin',
    'Cavalla',
    'Centaur',
    'Chang_Chun',
    'Chao_Ho',
    'Chapayev',
    'Charles_Ausburne',
    'Chaser',
    'Chicago',
    'Chitose',
    'Chiyoda',
    'Choukai',
    'Clevelad',
    'Cleveland',
    'Cleveland_',
    'Colorado',
    'Columbia',
    'Comet',
    'Concord',
    'Conte_di_Cavour',
    'Cooper',
    'Craven',
    'Crescent',
    'Curacoa',
    'Curlew',
    'Cygnet',
    'Dace',
    'Denver',
    'Deutschland',
    'Dewey',
    'Dido',
    'Dido_',
    'Dorsetshire',
    'Downes',
    'Duca_degli_Abruzzi',
    'Duke_of_York',
    'Dunkerque',
    'Eagle',
    'Echo',
    'Edinburgh',
    'Eldridge',
    'Émile_Bertin',
    'Enterprise',
    'Erebus',
    'Eskimo',
    'Essex',
    'Exeter',
    'Fiji',
    'Fletcher',
    'Foote',
    'Forbin',
    'Formidable',
    'Fortune',
    'Foxhound',
    'Fu_Shun',
    'Fubuki',
    'Fumizuki',
    'Furutaka',
    'Fusou',
    'Galatea',
    'Gangut',
    'Gascogne_',
    'Giulio_Cesare',
    'Glasgow',
    'Glorious',
    'Gloucester',
    'Glowworm',
    'Gneisenau',
    'Graf_Zeppelin',
    'Gremyashchy',
    'Grenville',
    'Gridley',
    'Gromky',
    'Grozny',
    'Halsey_Powell',
    'Hamakaze',
    'Hammann',
    'Hanazuki',
    'Hardy',
    'Haruna',
    'Harutsuki',
    'Hatakaze',
    'Hatsuharu',
    'Hatsushimo',
    'Hazelwood',
    'Helena',
    'Hermes',
    'Hermione',
    'Hibiki',
    'Hiei',
    'Hiei-chan',
    'Hiryuu',
    'Hiyou',
    'Hobby',
    'Honolulu',
    'Hood',
    'Hornet',
    'Houshou',
    'Houston',
    'Howe',
    'Hunter',
    'Hyuuga',
    'I-13',
    'I-168',
    'I-19',
    'I-25',
    'I-26',
    'I-56',
    'I-58',
    'Icarus',
    'Ikazuchi',
    'Illustrious',
    'Illustrious_',
    'Inazuma',
    'Independence',
    'Indianapolis',
    'Intrepid',
    'Ise',
    'Isokaze',
    'Isuzu',
    'Jamaica',
    'Javelin',
    'Jean_Bart',
    'Jeanne_dArc',
    'Jenkins',
    'Jersey',
    'Jintsuu',
    'Juneau',
    'Juno',
    'Junyou',
    'Jupiter',
    'Kaga',
    'Kaga_(Battleship)',
    'Kagerou',
    'Kako',
    'Kalk',
    'Kamikaze',
    'Karlsruhe',
    'Kashino',
    'Kasumi',
    'Kawakaze',
    'Kent',
    'Kii',
    'Kimberly',
    'King_George_V',
    'Kinu',
    'Kinugasa',
    'Kirishima',
    'Kirov',
    'Kisaragi',
    'Kiyonami',
    'Köln',
    'Kongou',
    'Königsberg',
    'Kumano',
    'Kuroshio',
    'La_Galissonnière',
    'Laffey',
    'Langley',
    'Le_Triomphant',
    'Le_Mars',
    'Le_Téméraire',
    'Le_Malin',
    'Le_Malin_',
    'Leander',
    'Leipzig',
    'Lena',
    'Lexington',
    'Libeccio',
    'Lil_Sandy',
    'Little_Bel',
    'Little_Renown',
    'Little_Illustrious',
    'Little_Enterprise',
    'Littorio',
    'London',
    'Long_Island',
    'LOpiniatre',
    'Maestrale',
    'Makinami',
    'Marblehead',
    'Maryland',
    'Massachusetts',
    'Matchless',
    'Matsukaze',
    'Maury',
    'Maya',
    'McCall',
    'Memphis',
    'Michishio',
    'Mikasa',
    'Mikazuki',
    'Mikuma',
    'Minazuki',
    'Minneapolis',
    'Minsk',
    'Mogami',
    'Montpelier',
    'Morrison',
    'Mullany',
    'Murmansk',
    'Musketeer',
    'Mutsu',
    'Mutsuki',
    'Myoukou',
    'Nachi',
    'Naganami',
    'Nagara',
    'Nagato',
    'Nagatsuki',
    'Naka',
    'Nelson',
    'Nevada',
    'New_Jersey',
    'Newcastle',
    'Nicholas',
    'Nicoloso_da_Recco',
    'Niizuki',
    'Ning_Hai',
    'Norfolk',
    'North_Carolina',
    'Northampton',
    'Noshiro',
    'Nowaki',
    'Nürnberg',
    'Oite',
    'Oklahoma',
    'Omaha',
    'Ooshio',
    'Oyashio',
    'Pamiat_Merkuria',
    'Penelope',
    'Pennsylvania',
    'Pensacola',
    'Perseus',
    'Peter_Strasser',
    'Phoenix',
    'Ping_Hai',
    'Pola',
    'Portland',
    'Prince_of_Wales',
    'Princeton',
    'Prinz_Eugen',
    'Prinz_Heinrich',
    'Prototype_Bulin_MKII',
    'Queen_Elizabeth',
    'Quincy',
    'Radford',
    'Raleigh',
    'Ranger',
    'Reno',
    'Renown',
    'Repulse',
    'Richelieu',
    'Richmond',
    'Rodney',
    'Roon_',
    'Ryuuhou',
    'Ryuujou',
    'Salt_Lake_City',
    'San_Diego',
    'San_Juan',
    'San_Francisco',
    'Saratoga',
    'Scharnhorst',
    'Sendai',
    'Shangri-La',
    'Sheffield',
    'Sheffield_',
    'Shigure',
    'Shinano',
    'Shiranui',
    'Shiratsuyu',
    'Shouhou',
    'Shoukaku',
    'Shropshire',
    'Sims',
    'Sirius',
    'Smalley',
    'Souryuu',
    'South_Dakota',
    'Southampton',
    'Sovetskaya_Belorussiya',
    'Sovetskaya_Rossiya',
    'Specialized_Bulin_Custom',
    'Spence',
    'St._Louis',
    'Stanly',
    'Stephen_Potter',
    'Stremitelny',
    'Suffolk',
    'Surcouf',
    'Suruga',
    'Sussex',
    'Suzutsuki',
    'Suzuya',
    'Swiftsure',
    'Tai_Yuan',
    'Taihou',
    'Taihou_',
    'Takao',
    'Tallinn',
    'Tanikaze',
    'Tartu',
    'Tashkent',
    'Tashkent_',
    'Tennessee',
    'Terror',
    'Thatcher',
    'Ticonderoga',
    'Tirpitz',
    'Torricelli',
    'Tosa',
    'Trento',
    'U-101',
    'U-110',
    'U-37',
    'U-410',
    'U-47',
    'U-522',
    'U-556',
    'U-557',
    'U-73',
    'U-81',
    'U-96',
    'Unicorn',
    'Universal_Bulin',
    'Urakaze',
    'Uranami',
    'Uzuki',
    'Valiant',
    'Vampire',
    'Vauquelin',
    'Vestal',
    'Victorious',
    'Vincennes',
    'Vincenzo_Gioberti',
    'Vittorio_Veneto',
    'Wakaba',
    'Warspite',
    'Washington',
    'Wasp',
    'Weser',
    'West_Virginia',
    'Wichita',
    'Yamashiro',
    'Yat_Sen',
    'Ying_Swei',
    'Yoizuki',
    'York',
    'Yorktown',
    'Yukikaze',
    'Yuubari',
    'Yuudachi',
    'Yuugure',
    'Z1',
    'Z18',
    'Z19',
    'Z2',
    'Z20',
    'Z21',
    'Z23',
    'Z24',
    'Z25',
    'Z26',
    'Z28',
    'Z35',
    'Z36',
    'Z46',
    'Zara',
    'Zeppy',
    'Zuikaku'
]

let shipsNum = document.querySelector('#shipsNum');
//let shipSelect = SHIPFUS[random];
const banner = document.querySelector('#banner');
const pool = document.getElementsByClassName('btn-check');



document.querySelector('#btnradio1').addEventListener('click', function(){
    if (pool[0].checked === true){
        banner.src = 'media/imgs/TilteScreen.png';
    }
});

document.querySelector('#btnradio2').addEventListener('click', function(){
    if (pool[1].checked === true){
        banner.src = 'media/imgs/kirishima-horn-ships.png';
    }
});

document.querySelector('#btnradio3').addEventListener('click', function(){
    if (pool[2].checked === true){
        banner.src = 'media/imgs/main-destroyers.png';
    }
});

document.querySelector('#btnradio4').addEventListener('click', function(){
    if (pool[3].checked === true){
        banner.src = 'media/imgs/tea-hermoione-perseus-chesire.png';
    }
});

document.querySelector('#buildBtn').addEventListener('click', function(){

    let parrafo = true;
    let borrarShips = document.querySelectorAll('.orderShip');

    if (borrarShips.length !== 0){
        for (let s of borrarShips){
            document.querySelector('#orders').removeChild(s);
        }
    }

    for (let i = 0; i<shipsNum.value; i++){
        
        //hay un pequeño bug con esto, si se genera la etiqueta <p> seguira existiendo porque nada la borra
        if (i > 4 && parrafo){ 
            document.querySelector('#orders').appendChild(document.createElement('p'));
            parrafo = false;
        }

        let ship = document.createElement('img');
        ship.src = `media/imgs/ships/70px-${SHIPFUS[random()]}Icon.png`;
        ship.className = 'orderShip';
        document.querySelector('#orders').appendChild(ship);
    }
    
})

function random(){
    let number = Math.round(Math.random() * 432);
    return number;
}

/*PARA ESTRUCTURAR MEJOR*/

class Pool{
    constructor(pool){
        this.pool = pool;
    }
}

class Ship{
    constructor(rareza, nombre){
        
    }
}